In [62]:
import numpy as np
import pandas as pd
import torch

``In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a.And matrices and tensors denoted as uppercase letters such as X or W.``

In [63]:
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [64]:
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [65]:
MATRIX = torch.tensor([[7, 7], [8, 8]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [66]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
`https://pytorch.org/docs/stable/generated/torch.rand.html`

In [67]:
random = torch.rand(4,4)
random

tensor([[0.3568, 0.8437, 0.1966, 0.0058],
        [0.6045, 0.7526, 0.1162, 0.5531],
        [0.0103, 0.3958, 0.5508, 0.4634],
        [0.0203, 0.0051, 0.6433, 0.7114]])

In [68]:
random.ndim

2

In [69]:
random.shape

torch.Size([4, 4])

##### Create an image 
###### color channel,Height, width

In [70]:
image_size_tensor = torch.rand(size=(3,224,224))
image_size_tensor.shape , image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [71]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
ten_zero = torch.zeros_like(input = one_to_ten)

In [73]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATA TYPES

In [74]:
example_tensor = torch.rand(3,4)
example_tensor

tensor([[0.7475, 0.1403, 0.4149, 0.9451],
        [0.2255, 0.1281, 0.6931, 0.4687],
        [0.3963, 0.5914, 0.8322, 0.3952]])

In [75]:
print(example_tensor)
print(f"data type of tensor: {example_tensor.dtype}")
print(f"shape of tensor: {example_tensor.shape}")
print(f"device tensor is on: {example_tensor.device}")

tensor([[0.7475, 0.1403, 0.4149, 0.9451],
        [0.2255, 0.1281, 0.6931, 0.4687],
        [0.3963, 0.5914, 0.8322, 0.3952]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [76]:
torch.cuda.is_available()

False

### Manipulating Tensors
Operations:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [77]:
new_tensor = torch.tensor([1,2,3])

In [78]:
# Addition
torch.add(new_tensor,10)
# new_tensor + 10

tensor([11, 12, 13])

In [79]:
# Subtraction
torch.sub(new_tensor,10)
# new_tensor - 10

tensor([-9, -8, -7])

In [80]:
# Multiplication
torch.mul(new_tensor,10)
# new_tensor * 10

tensor([10, 20, 30])

In [81]:
# Division
torch.div(new_tensor,10)
new_tensor

tensor([1, 2, 3])

### Matrix Multiplication
Two main ways of performing multiplication in NN and DL:
1. Element-wise
2. Matrix (dot product)

In [82]:
tensor1 = torch.tensor([[1,2,3]])
tensor2 = torch.tensor([[1],[2],[3]])

In [83]:
# 1. Element-wise
print(tensor1, "*", tensor1)
print(f"Equals: {tensor1 * tensor1}")

tensor([[1, 2, 3]]) * tensor([[1, 2, 3]])
Equals: tensor([[1, 4, 9]])


In [84]:
# 2. Matrix (dot product)
dot_product = torch.mm(tensor2, tensor1)
dot_product

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [85]:
torch.sub(tensor1,10)

tensor([[-9, -8, -7]])

In [86]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i]* tensor1[i]
print(value) 

tensor([1, 4, 9])
CPU times: total: 0 ns
Wall time: 1 ms


In [87]:
%%time
torch.matmul(new_tensor,new_tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [88]:
tensor2 @ tensor1

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [89]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2800, 0.2258, 0.0707],
        [0.2330, 0.1882, 0.0611],
        [0.2766, 0.2191, 0.0378]])

In [90]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [91]:
tensor_A.T 
#transpose 

tensor([[1, 3, 5],
        [2, 4, 6]])

In [92]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [93]:
print(f"min: {tensor_A.min()}")
print(f"max: {tensor_A.max()}")
print(f"average: {torch.mean(tensor_A.type(torch.float))}")
print(f"index position of min: {tensor_A.argmin()}")
print(f"index position of max: {tensor_A.argmax()}")

min: 1
max: 6
average: 3.5
index position of min: 0
index position of max: 5


In [94]:
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [95]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [96]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [97]:
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [98]:
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [99]:
x = torch.randn(2,3,5)
x, x.size()

(tensor([[[-8.3441e-01, -3.2539e-01, -4.2395e-01, -1.6037e+00, -1.2386e+00],
          [ 4.9564e-02, -4.5289e-01,  5.7726e-01,  1.9299e+00,  4.5747e-01],
          [ 8.3892e-01, -7.4341e-01, -3.4689e-01, -2.6912e-01, -2.5504e-01]],
 
         [[ 3.8073e-01,  5.9350e-01,  2.8130e+00,  1.2554e-01, -1.6647e+00],
          [-1.9909e-03, -7.7537e-01, -5.3012e-01, -4.6418e-01, -1.3056e+00],
          [-1.5808e+00,  1.0035e+00,  8.3447e-02,  1.4995e+00, -1.4935e+00]]]),
 torch.Size([2, 3, 5]))

In [100]:
permuted_x = torch.permute(x,(2,0,1))
permuted_x, permuted_x.size()

(tensor([[[-8.3441e-01,  4.9564e-02,  8.3892e-01],
          [ 3.8073e-01, -1.9909e-03, -1.5808e+00]],
 
         [[-3.2539e-01, -4.5289e-01, -7.4341e-01],
          [ 5.9350e-01, -7.7537e-01,  1.0035e+00]],
 
         [[-4.2395e-01,  5.7726e-01, -3.4689e-01],
          [ 2.8130e+00, -5.3012e-01,  8.3447e-02]],
 
         [[-1.6037e+00,  1.9299e+00, -2.6912e-01],
          [ 1.2554e-01, -4.6418e-01,  1.4995e+00]],
 
         [[-1.2386e+00,  4.5747e-01, -2.5504e-01],
          [-1.6647e+00, -1.3056e+00, -1.4935e+00]]]),
 torch.Size([5, 2, 3]))

In [101]:
x_original = torch.rand(size=(224,224,3)) # [height,width,color channel])
x_original

tensor([[[0.3953, 0.7007, 0.4661],
         [0.5974, 0.7064, 0.0205],
         [0.6073, 0.0688, 0.9073],
         ...,
         [0.5553, 0.8249, 0.3422],
         [0.6892, 0.0489, 0.7458],
         [0.9559, 0.9149, 0.1500]],

        [[0.9907, 0.4401, 0.6208],
         [0.4524, 0.3585, 0.5801],
         [0.7389, 0.2004, 0.1098],
         ...,
         [0.6505, 0.1635, 0.2070],
         [0.0550, 0.7368, 0.7910],
         [0.6921, 0.0150, 0.7438]],

        [[0.1723, 0.2070, 0.6470],
         [0.9971, 0.8474, 0.3454],
         [0.2672, 0.1706, 0.9123],
         ...,
         [0.5656, 0.9959, 0.2817],
         [0.7433, 0.7467, 0.0144],
         [0.3118, 0.4072, 0.7865]],

        ...,

        [[0.2947, 0.9562, 0.3669],
         [0.2750, 0.7521, 0.3774],
         [0.8998, 0.8013, 0.3858],
         ...,
         [0.9195, 0.0348, 0.4277],
         [0.7629, 0.5788, 0.8328],
         [0.7758, 0.9677, 0.9966]],

        [[0.3696, 0.0569, 0.0301],
         [0.1477, 0.2766, 0.0385],
         [0.

In [102]:
x_original_permuted = x_original.permute(2,0,1) 
x_original_permuted, x_original_permuted.size()

(tensor([[[0.3953, 0.5974, 0.6073,  ..., 0.5553, 0.6892, 0.9559],
          [0.9907, 0.4524, 0.7389,  ..., 0.6505, 0.0550, 0.6921],
          [0.1723, 0.9971, 0.2672,  ..., 0.5656, 0.7433, 0.3118],
          ...,
          [0.2947, 0.2750, 0.8998,  ..., 0.9195, 0.7629, 0.7758],
          [0.3696, 0.1477, 0.4077,  ..., 0.5854, 0.4824, 0.3990],
          [0.6009, 0.7367, 0.1271,  ..., 0.6819, 0.7538, 0.3620]],
 
         [[0.7007, 0.7064, 0.0688,  ..., 0.8249, 0.0489, 0.9149],
          [0.4401, 0.3585, 0.2004,  ..., 0.1635, 0.7368, 0.0150],
          [0.2070, 0.8474, 0.1706,  ..., 0.9959, 0.7467, 0.4072],
          ...,
          [0.9562, 0.7521, 0.8013,  ..., 0.0348, 0.5788, 0.9677],
          [0.0569, 0.2766, 0.3712,  ..., 0.6295, 0.1468, 0.2810],
          [0.3903, 0.0647, 0.6033,  ..., 0.9423, 0.0711, 0.9015]],
 
         [[0.4661, 0.0205, 0.9073,  ..., 0.3422, 0.7458, 0.1500],
          [0.6208, 0.5801, 0.1098,  ..., 0.2070, 0.7910, 0.7438],
          [0.6470, 0.3454, 0.9123,  ...,

# PyTorch Tensors & NumPy
* Data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [103]:
# Numpy array to tensor
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [104]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [105]:
torch.arange(1.,8.).dtype

torch.float32

In [106]:
tensor = torch.tensor([1,2,3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [107]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = torch.tensor([1,2,3])

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)
tensor_on_gpu.device

tensor([1, 2, 3])


device(type='cpu')

In [108]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)