In [1]:
import numpy as np
import pandas as pd
import torch

``In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a.And matrices and tensors denoted as uppercase letters such as X or W.``

In [2]:
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [3]:
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [4]:
MATRIX = torch.tensor([[7, 7], [8, 8]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [5]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
`https://pytorch.org/docs/stable/generated/torch.rand.html`

In [6]:
random = torch.rand(4,4)
random

tensor([[0.7337, 0.4746, 0.6358, 0.9135],
        [0.0417, 0.7450, 0.1136, 0.0055],
        [0.8722, 0.5068, 0.4692, 0.1139],
        [0.8105, 0.2134, 0.8840, 0.3130]])

In [7]:
random.ndim

2

In [8]:
random.shape

torch.Size([4, 4])

##### Create an image 
###### color channel,Height, width

In [9]:
image_size_tensor = torch.rand(size=(3,224,224))
image_size_tensor.shape , image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [10]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zero = torch.zeros_like(input = one_to_ten)

In [12]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATA TYPES

In [13]:
example_tensor = torch.rand(3,4)
example_tensor

tensor([[0.2869, 0.6036, 0.4617, 0.5765],
        [0.7145, 0.4503, 0.3165, 0.3352],
        [0.4738, 0.3861, 0.9439, 0.4212]])

In [14]:
print(example_tensor)
print(f"data type of tensor: {example_tensor.dtype}")
print(f"shape of tensor: {example_tensor.shape}")
print(f"device tensor is on: {example_tensor.device}")

tensor([[0.2869, 0.6036, 0.4617, 0.5765],
        [0.7145, 0.4503, 0.3165, 0.3352],
        [0.4738, 0.3861, 0.9439, 0.4212]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [15]:
torch.cuda.is_available()

False

### Manipulating Tensors
Operations:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [16]:
new_tensor = torch.tensor([1,2,3])

In [17]:
# Addition
torch.add(new_tensor,10)
# new_tensor + 10

tensor([11, 12, 13])

In [18]:
# Subtraction
torch.sub(new_tensor,10)
# new_tensor - 10

tensor([-9, -8, -7])

In [19]:
# Multiplication
torch.mul(new_tensor,10)
# new_tensor * 10

tensor([10, 20, 30])

In [20]:
# Division
torch.div(new_tensor,10)
new_tensor

tensor([1, 2, 3])

### Matrix Multiplication
Two main ways of performing multiplication in NN and DL:
1. Element-wise
2. Matrix (dot product)

In [21]:
tensor1 = torch.tensor([[1,2,3]])
tensor2 = torch.tensor([[1],[2],[3]])

In [22]:
# 1. Element-wise
print(tensor1, "*", tensor1)
print(f"Equals: {tensor1 * tensor1}")

tensor([[1, 2, 3]]) * tensor([[1, 2, 3]])
Equals: tensor([[1, 4, 9]])


In [23]:
# 2. Matrix (dot product)
dot_product = torch.mm(tensor2, tensor1)
dot_product

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [24]:
torch.sub(tensor1,10)

tensor([[-9, -8, -7]])

In [25]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i]* tensor1[i]
print(value) 

tensor([1, 4, 9])
CPU times: total: 0 ns
Wall time: 1.45 ms


In [26]:
%%time
torch.matmul(new_tensor,new_tensor)

CPU times: total: 0 ns
Wall time: 2.09 ms


tensor(14)

In [27]:
tensor2 @ tensor1

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [28]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1650, 0.3651, 0.5524],
        [0.2180, 0.4938, 0.7579],
        [0.3559, 0.6767, 0.9228]])

In [29]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [30]:
tensor_A.T 
#transpose 

tensor([[1, 3, 5],
        [2, 4, 6]])

In [31]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [32]:
print(f"min: {tensor_A.min()}")
print(f"max: {tensor_A.max()}")
print(f"average: {torch.mean(tensor_A.type(torch.float))}")
print(f"index position of min: {tensor_A.argmin()}")
print(f"index position of max: {tensor_A.argmax()}")

min: 1
max: 6
average: 3.5
index position of min: 0
index position of max: 5


In [33]:
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [34]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [35]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [36]:
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [37]:
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [38]:
x = torch.randn(2,3,5)
x, x.size()

(tensor([[[ 1.0860e+00,  9.0541e-01,  6.1393e-01,  2.3911e-01, -7.6759e-01],
          [-1.1967e+00, -4.5344e-01, -8.1595e-01, -2.2692e+00,  7.4939e-01],
          [ 3.1615e+00, -3.9618e-01,  6.5443e-01, -9.4576e-01, -1.7095e+00]],
 
         [[ 5.4287e-01,  4.2422e-02,  1.7008e+00,  1.1100e-05, -4.3450e-01],
          [ 6.2674e-01, -5.4209e-01,  1.1623e+00, -7.8512e-02,  1.5454e+00],
          [ 1.6311e+00, -1.2915e+00,  2.0826e+00, -5.1877e-01, -7.5276e-01]]]),
 torch.Size([2, 3, 5]))

In [39]:
permuted_x = torch.permute(x,(2,0,1))
permuted_x, permuted_x.size()

(tensor([[[ 1.0860e+00, -1.1967e+00,  3.1615e+00],
          [ 5.4287e-01,  6.2674e-01,  1.6311e+00]],
 
         [[ 9.0541e-01, -4.5344e-01, -3.9618e-01],
          [ 4.2422e-02, -5.4209e-01, -1.2915e+00]],
 
         [[ 6.1393e-01, -8.1595e-01,  6.5443e-01],
          [ 1.7008e+00,  1.1623e+00,  2.0826e+00]],
 
         [[ 2.3911e-01, -2.2692e+00, -9.4576e-01],
          [ 1.1100e-05, -7.8512e-02, -5.1877e-01]],
 
         [[-7.6759e-01,  7.4939e-01, -1.7095e+00],
          [-4.3450e-01,  1.5454e+00, -7.5276e-01]]]),
 torch.Size([5, 2, 3]))

In [40]:
x_original = torch.rand(size=(224,224,3)) # [height,width,color channel])
x_original

tensor([[[6.1702e-01, 1.1022e-01, 9.1956e-01],
         [4.1374e-01, 4.8878e-01, 9.3334e-01],
         [7.7332e-01, 4.0409e-01, 6.1208e-01],
         ...,
         [8.0714e-01, 4.1051e-01, 3.1832e-01],
         [6.0952e-02, 4.4256e-01, 7.8884e-01],
         [9.0606e-01, 4.9681e-01, 1.9293e-01]],

        [[5.6874e-01, 4.9258e-02, 4.5374e-01],
         [6.1556e-01, 5.5011e-01, 9.8961e-01],
         [4.0243e-01, 7.5979e-02, 8.2904e-02],
         ...,
         [5.5437e-01, 2.9053e-01, 2.2829e-01],
         [9.6690e-01, 8.5865e-01, 7.1300e-01],
         [8.6289e-01, 6.5039e-01, 9.9101e-01]],

        [[5.5537e-01, 8.6744e-01, 6.0492e-01],
         [6.3834e-01, 9.0738e-01, 1.5059e-01],
         [2.4472e-01, 9.7093e-01, 2.1115e-01],
         ...,
         [5.3960e-01, 8.2851e-01, 5.2790e-01],
         [3.7212e-01, 1.0230e-01, 5.7964e-01],
         [1.2054e-01, 4.3032e-01, 2.9416e-01]],

        ...,

        [[3.2608e-01, 3.0432e-01, 7.1591e-01],
         [8.9477e-01, 7.3255e-01, 9.8460e-02]

In [41]:
x_original_permuted = x_original.permute(2,0,1) 
x_original_permuted, x_original_permuted.size()

(tensor([[[6.1702e-01, 4.1374e-01, 7.7332e-01,  ..., 8.0714e-01,
           6.0952e-02, 9.0606e-01],
          [5.6874e-01, 6.1556e-01, 4.0243e-01,  ..., 5.5437e-01,
           9.6690e-01, 8.6289e-01],
          [5.5537e-01, 6.3834e-01, 2.4472e-01,  ..., 5.3960e-01,
           3.7212e-01, 1.2054e-01],
          ...,
          [3.2608e-01, 8.9477e-01, 3.0067e-01,  ..., 7.2014e-01,
           7.1543e-01, 2.4750e-01],
          [3.3747e-01, 3.9501e-01, 9.6153e-01,  ..., 5.8287e-04,
           2.9177e-01, 1.6987e-01],
          [8.8468e-01, 1.1618e-01, 9.3041e-01,  ..., 6.5393e-01,
           2.6140e-01, 1.0605e-01]],
 
         [[1.1022e-01, 4.8878e-01, 4.0409e-01,  ..., 4.1051e-01,
           4.4256e-01, 4.9681e-01],
          [4.9258e-02, 5.5011e-01, 7.5979e-02,  ..., 2.9053e-01,
           8.5865e-01, 6.5039e-01],
          [8.6744e-01, 9.0738e-01, 9.7093e-01,  ..., 8.2851e-01,
           1.0230e-01, 4.3032e-01],
          ...,
          [3.0432e-01, 7.3255e-01, 6.0289e-01,  ..., 1.828

# PyTorch Tensors & NumPy
* Data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [42]:
# Numpy array to tensor
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [44]:
torch.arange(1.,8.).dtype

torch.float32

In [45]:
tensor = torch.tensor([1,2,3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [46]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = torch.tensor([1,2,3])

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)
tensor_on_gpu.device

tensor([1, 2, 3])


device(type='cpu')

In [47]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)