## Exercises
1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on ``torch.Tensor`` and for ``torch.cuda``.

2. Create a random tensor with shape (7, 7).

In [2]:
import torch

In [4]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.9677, 0.6040, 0.2190, 0.2185, 0.2812, 0.4416, 0.4686],
        [0.4825, 0.0299, 0.9950, 0.4668, 0.0354, 0.1593, 0.2981],
        [0.0642, 0.2984, 0.2728, 0.2211, 0.3509, 0.2261, 0.8649],
        [0.9017, 0.9750, 0.5469, 0.4198, 0.7712, 0.8782, 0.6161],
        [0.8811, 0.7158, 0.5584, 0.0392, 0.5767, 0.3461, 0.7529],
        [0.1554, 0.0350, 0.5982, 0.7206, 0.8133, 0.0089, 0.8382],
        [0.9872, 0.0769, 0.8479, 0.5842, 0.2109, 0.7439, 0.8483]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [6]:
other_random_tensor = torch.rand(1,7)

In [7]:
torch.mm(other_random_tensor,random_tensor)

tensor([[2.5888, 1.2167, 2.3064, 1.4393, 1.3723, 1.3420, 2.4516]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [10]:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
other_random_tensor = torch.rand(1,7)

In [11]:
torch.mm(other_random_tensor,random_tensor)

tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])

6.  Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [32]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(1234)
tensor1 = torch.randn(2, 3, device=device)
tensor2 = torch.randn(2, 3, device=device)

In [17]:
print("Tensor 1 on GPU:", tensor1)
print("Tensor 2 on GPU:", tensor2)

Tensor 1 on GPU: tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
Tensor 2 on GPU: tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])


###### Yapılması istenen işlem cpu da gerçekleşti. Gpu da değil.

In [19]:
tensor1.device

device(type='cpu')

In [20]:
tensor2.device

device(type='cpu')

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [33]:
result = torch.mm(tensor1.T, tensor2)
result

tensor([[ 0.4828,  0.0541, -0.0684],
        [-1.2409,  0.2164,  0.0512],
        [ 0.8635, -0.6496,  0.1395]])

8. Find the maximum and minimum values of the output of 7.  

In [40]:
max_value = torch.max(result)
min_value = torch.min(result)

In [41]:
print(f"max value : {max_value}")
print(f"min value : {min_value}")

max value : 0.8634691834449768
min value : -1.2408744096755981


9. Find the maximum and minimum index values of the output of 7.

In [42]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)

In [45]:
print(f"max index : {max_index}")
print(f"min index : {min_index}")

max index : 6
min index : 3


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [47]:
torch.manual_seed(7)

In [52]:
tensor1 = torch.randn(1,1,1,10)
tensor1, tensor1.size()

(tensor([[[[ 1.7792, -0.9179, -0.4578, -0.7245,  1.2799, -0.9941,  1.8150,
            -0.6028,  1.6148,  1.9302]]]]),
 torch.Size([1, 1, 1, 10]))

In [54]:
tensor2 = tensor1.squeeze()
tensor2, tensor2.size()

(tensor([ 1.7792, -0.9179, -0.4578, -0.7245,  1.2799, -0.9941,  1.8150, -0.6028,
          1.6148,  1.9302]),
 torch.Size([10]))