## Exercises
1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on ``torch.Tensor`` and for ``torch.cuda``.

2. Create a random tensor with shape (7, 7).

In [1]:
import torch

In [2]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[5.5087e-04, 7.5735e-01, 7.7561e-01, 6.2054e-01, 2.7732e-02, 1.1632e-01,
         9.9963e-01],
        [1.0177e-02, 2.1668e-01, 7.7999e-01, 1.9228e-01, 3.3128e-01, 3.8935e-01,
         7.7241e-01],
        [5.9894e-01, 9.8490e-01, 5.9006e-02, 9.0627e-01, 3.3466e-01, 3.6928e-01,
         5.5998e-01],
        [7.1475e-01, 5.5935e-01, 8.4256e-01, 2.4173e-02, 6.7148e-01, 3.5015e-02,
         9.8896e-01],
        [4.1218e-01, 5.2665e-01, 4.2396e-01, 8.3608e-01, 4.5780e-01, 9.8629e-02,
         4.5973e-01],
        [2.0554e-01, 6.9753e-01, 6.1090e-01, 5.3343e-02, 8.7704e-02, 3.1529e-01,
         7.0157e-01],
        [2.4199e-01, 7.3159e-01, 2.7941e-01, 9.8871e-02, 7.8162e-01, 4.1903e-01,
         3.9989e-01]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
other_random_tensor = torch.rand(1,7)

In [4]:
torch.mm(other_random_tensor,random_tensor)

tensor([[1.2446, 2.1526, 1.2954, 1.2671, 1.2086, 0.8022, 1.9429]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [5]:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
other_random_tensor = torch.rand(1,7)

In [6]:
torch.mm(other_random_tensor,random_tensor)

tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])

6.  Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(1234)
tensor1 = torch.randn(2, 3, device=device)
tensor2 = torch.randn(2, 3, device=device)

In [8]:
print("Tensor 1 on GPU:", tensor1)
print("Tensor 2 on GPU:", tensor2)

Tensor 1 on GPU: tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
Tensor 2 on GPU: tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])


###### Yapılması istenen işlem cpu da gerçekleşti. Gpu da değil.

In [9]:
tensor1.device

device(type='cpu')

In [10]:
tensor2.device

device(type='cpu')

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [11]:
result = torch.mm(tensor1.T, tensor2)
result

tensor([[ 0.4828,  0.0541, -0.0684],
        [-1.2409,  0.2164,  0.0512],
        [ 0.8635, -0.6496,  0.1395]])

8. Find the maximum and minimum values of the output of 7.  

In [12]:
max_value = torch.max(result)
min_value = torch.min(result)

In [13]:
print(f"max value : {max_value}")
print(f"min value : {min_value}")

max value : 0.8634691834449768
min value : -1.2408744096755981


9. Find the maximum and minimum index values of the output of 7.

In [14]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)

In [15]:
print(f"max index : {max_index}")
print(f"min index : {min_index}")

max index : 6
min index : 3


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
torch.manual_seed(7)

In [17]:
tensor1 = torch.randn(1,1,1,10)
tensor1, tensor1.size()

(tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
             1.2324,  0.1382, -1.6822]]]]),
 torch.Size([1, 1, 1, 10]))

In [18]:
tensor2 = tensor1.squeeze()
tensor2, tensor2.size()

(tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
          0.1382, -1.6822]),
 torch.Size([10]))