In [1]:
import numpy as np
import pandas as pd
import torch

``In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a.And matrices and tensors denoted as uppercase letters such as X or W.``

In [2]:
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [3]:
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [4]:
MATRIX = torch.tensor([[7, 7], [8, 8]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [5]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
`https://pytorch.org/docs/stable/generated/torch.rand.html`

In [6]:
random = torch.rand(4,4)
random

tensor([[0.0172, 0.5331, 0.0299, 0.3976],
        [0.1231, 0.2932, 0.2838, 0.5982],
        [0.4833, 0.1252, 0.3760, 0.1084],
        [0.2377, 0.1128, 0.5038, 0.1369]])

In [7]:
random.ndim

2

In [8]:
random.shape

torch.Size([4, 4])

##### Create an image 
###### color channel,Height, width

In [9]:
image_size_tensor = torch.rand(size=(3,224,224))
image_size_tensor.shape , image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [10]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zero = torch.zeros_like(input = one_to_ten)

In [12]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATA TYPES

In [13]:
example_tensor = torch.rand(3,4)
example_tensor

tensor([[0.9439, 0.8301, 0.1038, 0.2336],
        [0.3574, 0.9767, 0.4054, 0.1671],
        [0.7543, 0.1132, 0.6985, 0.6166]])

In [14]:
print(example_tensor)
print(f"data type of tensor: {example_tensor.dtype}")
print(f"shape of tensor: {example_tensor.shape}")
print(f"device tensor is on: {example_tensor.device}")

tensor([[0.9439, 0.8301, 0.1038, 0.2336],
        [0.3574, 0.9767, 0.4054, 0.1671],
        [0.7543, 0.1132, 0.6985, 0.6166]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [15]:
torch.cuda.is_available()

False

### Manipulating Tensors
Operations:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [16]:
new_tensor = torch.tensor([1,2,3])

In [17]:
# Addition
torch.add(new_tensor,10)
# new_tensor + 10

tensor([11, 12, 13])

In [18]:
# Subtraction
torch.sub(new_tensor,10)
# new_tensor - 10

tensor([-9, -8, -7])

In [19]:
# Multiplication
torch.mul(new_tensor,10)
# new_tensor * 10

tensor([10, 20, 30])

In [20]:
# Division
torch.div(new_tensor,10)
new_tensor

tensor([1, 2, 3])

### Matrix Multiplication
Two main ways of performing multiplication in NN and DL:
1. Element-wise
2. Matrix (dot product)

In [35]:
tensor1 = torch.tensor([[1,2,3]])
tensor2 = torch.tensor([[1],[2],[3]])

In [36]:
# 1. Element-wise
print(tensor1, "*", tensor1)
print(f"Equals: {tensor1 * tensor1}")

tensor([[1, 2, 3]]) * tensor([[1, 2, 3]])
Equals: tensor([[1, 4, 9]])


In [44]:
# 2. Matrix (dot product)
dot_product = torch.mm(tensor2, tensor1)
dot_product

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [26]:
torch.sub(tensor1,10)

tensor([[-9, -8, -7]])

In [38]:
%%time
value = 0
for i in range(len(tensor1)):
    value += tensor1[i]* tensor1[i]
print(value) 

tensor([1, 4, 9])
CPU times: total: 0 ns
Wall time: 0 ns


In [40]:
%%time
torch.matmul(new_tensor,new_tensor)

CPU times: total: 0 ns
Wall time: 996 µs


tensor(14)

In [42]:
tensor2 @ tensor1

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [55]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4716, 0.3120, 0.3590],
        [0.6419, 0.6204, 0.4464],
        [0.3933, 0.3481, 0.2804]])

In [56]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [61]:
tensor_A.T 
#transpose 

tensor([[1, 3, 5],
        [2, 4, 6]])

In [60]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [72]:
print(f"min: {tensor_A.min()}")
print(f"max: {tensor_A.max()}")
print(f"average: {torch.mean(tensor_A.type(torch.float))}")
print(f"index position of min: {tensor_A.argmin()}")
print(f"index position of max: {tensor_A.argmax()}")

min: 1
max: 6
average: 3.5
index position of min: 0
index position of max: 5


In [73]:
x = torch.arange(1.,11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [74]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [78]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [80]:
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [87]:
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [90]:
x = torch.randn(2,3,5)
x, x.size()

(tensor([[[-0.4485,  0.0135,  1.8106, -0.7445,  2.0462],
          [-0.4672, -0.0811,  0.6835, -1.1476,  0.8266],
          [ 0.4258, -0.5910, -0.2004,  0.0308,  0.6152]],
 
         [[ 0.4837, -0.9391, -1.2369, -0.7336,  0.2037],
          [ 0.6138, -1.6105,  1.2727, -0.8931, -0.1836],
          [ 0.8556,  0.3869, -0.8175, -0.6155,  0.1386]]]),
 torch.Size([2, 3, 5]))

In [93]:
permuted_x = torch.permute(x,(2,0,1))
permuted_x, permuted_x.size()

(tensor([[[-0.4485, -0.4672,  0.4258],
          [ 0.4837,  0.6138,  0.8556]],
 
         [[ 0.0135, -0.0811, -0.5910],
          [-0.9391, -1.6105,  0.3869]],
 
         [[ 1.8106,  0.6835, -0.2004],
          [-1.2369,  1.2727, -0.8175]],
 
         [[-0.7445, -1.1476,  0.0308],
          [-0.7336, -0.8931, -0.6155]],
 
         [[ 2.0462,  0.8266,  0.6152],
          [ 0.2037, -0.1836,  0.1386]]]),
 torch.Size([5, 2, 3]))

In [96]:
x_original = torch.rand(size=(224,224,3)) # [height,width,color channel])
x_original

tensor([[[0.9547, 0.6442, 0.4379],
         [0.7089, 0.7503, 0.1440],
         [0.4903, 0.7440, 0.0623],
         ...,
         [0.2154, 0.8476, 0.1565],
         [0.9902, 0.7689, 0.9860],
         [0.5260, 0.6039, 0.4556]],

        [[0.0486, 0.9681, 0.8967],
         [0.4607, 0.0821, 0.4803],
         [0.0425, 0.3052, 0.6400],
         ...,
         [0.8813, 0.2316, 0.9772],
         [0.8181, 0.4710, 0.7241],
         [0.8517, 0.6776, 0.3930]],

        [[0.2451, 0.2757, 0.7205],
         [0.5009, 0.8537, 0.3244],
         [0.2643, 0.2317, 0.0933],
         ...,
         [0.8876, 0.3832, 0.6593],
         [0.0722, 0.9619, 0.5728],
         [0.5432, 0.5286, 0.7631]],

        ...,

        [[0.0822, 0.6314, 0.4079],
         [0.6223, 0.4678, 0.9126],
         [0.6775, 0.4134, 0.3370],
         ...,
         [0.0237, 0.6919, 0.7000],
         [0.1224, 0.2392, 0.0726],
         [0.0625, 0.5586, 0.1735]],

        [[0.1547, 0.3241, 0.4100],
         [0.3271, 0.3648, 0.9200],
         [0.

In [100]:
x_original_permuted = x_original.permute(2,0,1) 
x_original_permuted, x_original_permuted.size()

(tensor([[[0.9547, 0.7089, 0.4903,  ..., 0.2154, 0.9902, 0.5260],
          [0.0486, 0.4607, 0.0425,  ..., 0.8813, 0.8181, 0.8517],
          [0.2451, 0.5009, 0.2643,  ..., 0.8876, 0.0722, 0.5432],
          ...,
          [0.0822, 0.6223, 0.6775,  ..., 0.0237, 0.1224, 0.0625],
          [0.1547, 0.3271, 0.1852,  ..., 0.2414, 0.0653, 0.8496],
          [0.9467, 0.3529, 0.4320,  ..., 0.3614, 0.8204, 0.6935]],
 
         [[0.6442, 0.7503, 0.7440,  ..., 0.8476, 0.7689, 0.6039],
          [0.9681, 0.0821, 0.3052,  ..., 0.2316, 0.4710, 0.6776],
          [0.2757, 0.8537, 0.2317,  ..., 0.3832, 0.9619, 0.5286],
          ...,
          [0.6314, 0.4678, 0.4134,  ..., 0.6919, 0.2392, 0.5586],
          [0.3241, 0.3648, 0.9639,  ..., 0.7710, 0.7984, 0.9394],
          [0.9279, 0.1739, 0.5492,  ..., 0.2409, 0.3709, 0.9699]],
 
         [[0.4379, 0.1440, 0.0623,  ..., 0.1565, 0.9860, 0.4556],
          [0.8967, 0.4803, 0.6400,  ..., 0.9772, 0.7241, 0.3930],
          [0.7205, 0.3244, 0.0933,  ...,